# Generated by Django 2.0.2 on 2018-02-20 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('nric', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 2, 20, 11, 49, 32, 16048, tzinfo=utc))),
            ],
        ),
    ]
