# Generated by Django 2.0.3 on 2018-03-10 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0003_auto_20180310_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='randomcode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 10, 18, 12, 39, 247384, tzinfo=utc)),
        ),
    ]
