# Generated by Django 2.0.3 on 2018-04-03 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realapp', '0004_auto_20180311_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='digicard',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='photoverify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 9, 2, 13, 61352, tzinfo=utc)),
        ),
    ]
