# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date published',
        ),
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 13, 45, 30, 160249, tzinfo=utc), verbose_name=b'date published'),
        ),
    ]
