# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180207_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='date published',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 13, 45, 50, 153852, tzinfo=utc)),
        ),
    ]
