# Generated by Django 2.0.3 on 2018-03-10 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180310_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 10, 18, 12, 39, 241395, tzinfo=utc), verbose_name='date published'),
        ),
    ]
