# Generated by Django 2.0.3 on 2018-04-16 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180403_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 16, 6, 33, 27, 140399, tzinfo=utc), verbose_name='date published'),
        ),
    ]
